services:
  Eshopping:
    build: .
    image: eshopping_image
    container_name: eshopping_container
    ports:
      - 8082:8080
    environment:
      - 'MYSQL_HOST=db'
      - 'MYSQL_PORT=3306'
      - 'MYSQL_ROOT_PASSWORD=0000'
      - 'MYSQL_USER=root'
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: mysql_container
    ports:
      - 3307:3306
    environment:
      - 'MYSQL_DATABASE=eshopping'
      - 'MYSQL_ROOT_PASSWORD=0000'
    volumes:
      - d:/data/:/var/lib/mysql